kind: pipeline
type: docker
name: default

trigger:
    event: [push, pull_request]

steps:
    - name: pre-commit
      image: python:3.9
      environment:
          PIP_CACHE_DIR: ./.cache/pip
          PRE_COMMIT_HOME: ./.cache/pre-commit
      commands:
          - pip install --upgrade pip
          - pip install -r requirements_dev.txt
          - pip install pre-commit
          - pre-commit run --all-files

    - name: unit test
      image: python:3.9
      commands:
          - pip install --upgrade pip
          - pip install -r requirements_test.txt
          - export PYTHONPATH=$PYTHONPATH:$(pwd)/ilovepdf-python
          - pytest tests/unit

    - name: integration test
      image: python:3.9
      commands:
          - pip install -r requirements_test.txt
          - export PYTHONPATH=$PYTHONPATH:$(pwd)/ilovepdf-python
          - pytest tests/integration
#nota1,2,3,4
