[project]
name = "ilovepdf"
description = "iLovePDF Python API"
version = "0.0.1"
authors = [{ name = "ilovepdf", email = "info@ilovepdf.com" }]
license = "MIT"
readme = "README.md"

requires-python = ">=3.10"
dependencies = ["requests>=2.28.0", "pyjwt>=2.4.0", "python-dotenv>=1.0.0"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: Python :: 3 :: Only",
]

[project.urls]
Documentation = "https://developer.ilovepdf.com/docs"
Homepage = "https://ilovepdf.com/"

[tool.setuptools.packages.find]
where = ["."]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.pytest.ini_options]
pythonpath = ["ilovepdf"]
testpaths = ["tests"]
python_files = ["test_*.py", "*_test.py"]
addopts = "--color=yes -vv --reruns 1 --reruns-delay 3 --tb=short"
log_cli = true
log_cli_level = "INFO"

[tool.ruff]
line-length = 88
target-version = "py310"
extend-exclude = ["samples/"]

[tool.ruff.lint]
select = ["E", "F", "I", "B", "S", "UP"]


[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101", "S105" , "S106"]

[tool.pyright]
include = ["ilovepdf", "tests", "samples"]
exclude = [
    "**/venv", "**/.venv", "**/build", "**/dist",
    "**/.pytest_cache", "**/__pycache__"
]
pythonVersion = "3.10"
pythonPlatform = "Linux"
typeCheckingMode = "basic"
reportDeprecated = true

reportMissingImports = true
