[project]
name = "ilovepdf"
description = "iLovePDF Python API"
version = "0.0.1"
authors = [{ name = "ilovepdf", email = "info@ilovepdf.com" }]
license = { file = "LICENSE" }
readme = "README.md"

requires-python = ">=3.9"
dependencies = ["requests>=2.28.0", "pyjwt>=2.4.0"]

[project.urls]
Documentation = "https://developer.ilovepdf.com/docs"
Homepage = "https://ilovepdf.com/"

[tool.setuptools.packages.find]
where = ["."]

[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.flake8]
exclude = ".git,future,venv"
max-line-length = 119

[tool.pylint.format]
max-line-length = 119

[tool.pylint."MESSAGES CONTROL"]
disable = ["C0116"]

[tool.pylint.master]
ignore = ["samples"]
